name = "worker-ias"
main = "./src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "IAS_CACHE"
id = "fb98c02d911c416db3ff592f23d81ceb"

[vars]
GITHUB_REPO = "businesbrazilbr-boop/i-a-trend"
GITHUB_BRANCH = "main"
DAILY_LIMIT = "10"
CONTENT_PATH = "src/content/news"
SITE_URL = "https://i-a-trend.com"
ENVIRONMENT = "production"

[triggers]
crons = ["*/30 * * * *"]